Improve dev setup instructions
p15r/distributey pull request #97
Opened 2021-10-28 11:28 UTC by in0rdr

Setting up a new dev environment on my local machine. This PR documents the changes I would like to see regarding the setup from scratch.

- Dev files are not generated if dev mode is not activated
- Some more explanation is needed regarding the certificate to validate the JWT keys. The keys need to be placed on Distributey and the Vault server side.

2021-11-24 20:05 UTC, p15r commented
@in0rdr my GH notifications didn't work - sorry for the delayed response. What actually changed in docs/cache-only-key-service-v3.xml?

2021-11-24 20:07 UTC, p15r commented on docs/key_consumer_setup.md
> +     - Store the same public `jwt_kid_salesforce_serviceX.pub` key on the Vault JWT auth backend as part of `auth_jwt_validation_pubkeys` in the Terraform variables ([`./docker/terraform/terraform.tf
Can you mention that this is done (automatically) by `dev/write_jwt_to_tfvars.py` which is called by `dev/dev_setup.sh`?

I appreciate the callout about the production setup!

2021-11-24 20:08 UTC, p15r requested changes
Great input 🙏

2021-11-25 15:04 UTC, in0rdr commented
> @in0rdr my GH notifications didn't work - sorry for the delayed response. What actually changed in docs/cache-only-key-service-v3.xml?

I removed a reference to AppRole authentication from the picture. It's JWT only authenticaiton, all the way (from src to dest).

2021-12-02 08:57 UTC, merged